# Generated by Django 5.0.4 on 2024-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email_address',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
