# Generated by Django 5.0.4 on 2024-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0005_alter_cat_catowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='catImage',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
    ]
