# Generated by Django 5.0.4 on 2024-04-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0007_remove_cat_catimage_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='catImage',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catOwner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.owner'),
        ),
        migrations.DeleteModel(
            name='CatImage',
        ),
    ]
