# Generated by Django 5.0.4 on 2024-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0008_cat_catimage_alter_cat_catowner_delete_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catImage', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
