# Generated by Django 5.0.4 on 2024-04-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0009_catimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='catImage',
            field=models.ImageField(default=None, null=True, upload_to='post_images'),
        ),
    ]
