# Generated by Django 5.0.4 on 2024-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0012_cat_catgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='catAge',
            field=models.CharField(max_length=200),
        ),
    ]
