# Generated by Django 5.0.4 on 2024-04-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0013_alter_cat_catage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='catOwner',
        ),
    ]
