# Generated by Django 5.0.4 on 2024-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0014_remove_cat_catowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='catAge',
            new_name='CatAge',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catBreed',
            new_name='CatBreed',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catDislikes',
            new_name='CatDislikes',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catGender',
            new_name='CatGender',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catImage',
            new_name='CatImage',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catLikes',
            new_name='CatLikes',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catName',
            new_name='CatName',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='catPersonality',
            new_name='CatPersonality',
        ),
    ]
