# Generated by Django 5.0.4 on 2024-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0015_rename_catage_cat_catage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='CatColor',
            field=models.CharField(default='orange', max_length=200),
        ),
    ]
