# Generated by Django 5.0.4 on 2024-04-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0016_cat_catcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='CatOwner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.owner'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='CatAge',
            field=models.IntegerField(),
        ),
    ]
