# Generated by Django 5.0.4 on 2024-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0017_cat_catowner_alter_cat_catage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='CatDescription',
            field=models.CharField(default='No Input', max_length=1000),
        ),
    ]
