# Generated by Django 5.0.4 on 2024-04-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0019_cat_catbirthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='favoriteCats',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='djangoback.cat'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='catOwner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.owner'),
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoptedCat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.cat')),
                ('ownerAccount', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.owner')),
            ],
        ),
    ]
