# Generated by Django 5.0.4 on 2024-05-15 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0020_accounts_favoritecats_alter_accounts_catowner_adopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='CatOwner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoback.accounts'),
        ),
    ]
