# Generated by Django 5.0.4 on 2024-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoback', '0022_accounts_address_accounts_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='CatAdoption',
            field=models.BooleanField(default=False),
        ),
    ]
