# Generated by Django 5.0.3 on 2024-03-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='name',
        ),
    ]
