# Generated by Django 5.0.3 on 2024-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
    ]
